/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Ecommerce
 * API do sistema de e-commerce
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { LoginAdminRequestDto, LoginAdminResponseDto } from '.././model';

/**
 * @summary Login de administrador
 */
export const loginAdmin = (
  loginAdminRequestDto: LoginAdminRequestDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<LoginAdminResponseDto>> => {
  return axios.post(`/auth/admin/login`, loginAdminRequestDto, options);
};

export const getLoginAdminMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginAdmin>>,
    TError,
    { data: LoginAdminRequestDto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginAdmin>>,
  TError,
  { data: LoginAdminRequestDto },
  TContext
> => {
  const mutationKey = ['loginAdmin'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginAdmin>>,
    { data: LoginAdminRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return loginAdmin(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginAdmin>>
>;
export type LoginAdminMutationBody = LoginAdminRequestDto;
export type LoginAdminMutationError = AxiosError<void>;

/**
 * @summary Login de administrador
 */
export const useLoginAdmin = <TError = AxiosError<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginAdmin>>,
      TError,
      { data: LoginAdminRequestDto },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof loginAdmin>>,
  TError,
  { data: LoginAdminRequestDto },
  TContext
> => {
  const mutationOptions = getLoginAdminMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
