/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Ecommerce
 * API do sistema de e-commerce
 * OpenAPI spec version: 1.0
 */

export interface LoginAdminResponseDto {
  /** Token JWT para autenticação */
  token: string;
}
